In [1]:
print("hello world")

hello world


In [1]:
import numpy as np 

In [5]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr.dtype

dtype('int64')

In [9]:
arr = np.array([10,20,30,40,50,20.2])   # to create an array 
arr 

array([10. , 20. , 30. , 40. , 50. , 20.2])

In [10]:
arr = np.array([10,20,30,40,50,"Upflairs"])   # to create an array 
arr 

array(['10', '20', '30', '40', '50', 'Upflairs'], dtype='<U21')

In [13]:
arr.ndim    # dimension of array 

1

In [14]:
arr = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])   # [ [1d] , [1d] , [1D] , [1D]  ]
arr 

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [18]:
ls = [[[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]]]

# print(ls)
# print(type(ls))
arr = np.array(ls)
arr 

array([[[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [19]:
type(arr)

numpy.ndarray

In [20]:
arr.ndim 

3

In [3]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [23]:
arr[-2]  # single item 

np.int64(40)

In [27]:
arr[::3]

array([10, 40])

In [28]:
arr[::1]

array([10, 20, 30, 40, 50])

In [29]:
arr[::-1]


array([50, 40, 30, 20, 10])

In [4]:
arr 

array([10, 20, 30, 40, 50])

In [5]:
arr = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])   # [ [1d] , [1d] , [1D] , [1D]  ]
arr 

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [6]:
arr = np.random.randint(1,50,(3,5,4))  #  
arr 

array([[[ 6,  9, 29, 24],
        [47, 32, 39, 46],
        [36, 25, 41, 24],
        [12,  2,  9,  6],
        [14, 43, 37, 22]],

       [[49, 21, 48,  6],
        [12, 40, 32, 34],
        [ 9,  2, 49, 13],
        [46,  2,  7, 16],
        [24, 37, 37, 29]],

       [[32, 26, 26,  9],
        [ 4, 32,  5,  9],
        [26,  5, 14, 26],
        [27, 25, 18, 47],
        [ 5,  2, 22, 26]]], dtype=int32)

In [8]:
arr = np.random.randint(1,50,10)  # 1D array creating with randomly 
arr 

array([11, 13, 14,  1,  9, 15, 17, 41,  8,  3], dtype=int32)

In [11]:
arr = np.random.randint(1,50,(5,8))  # 2D array creating with randomly 
arr 

array([[29,  6,  6, 42, 29, 14, 11, 32],
       [ 5, 30, 36, 19,  4, 35, 37, 23],
       [43, 49, 28, 23, 36, 21, 33, 37],
       [24,  1, 12,  8, 17, 13, 22, 32],
       [ 6, 41, 48,  6, 31, 12, 26, 20]], dtype=int32)

In [12]:
arr.shape  

(5, 8)

In [17]:
arr = np.random.randint(1,50,(3,4,3))  # 3D array creating with randomly 
arr 

array([[[42, 23, 16],
        [29, 24,  4],
        [11,  7, 35],
        [ 1, 15, 24]],

       [[37, 28, 15],
        [20,  3, 21],
        [27, 20, 29],
        [25,  9, 17]],

       [[25, 11, 11],
        [28,  8, 31],
        [25, 48, 14],
        [ 5, 41, 23]]], dtype=int32)

In [19]:
arr = np.random.random(10)
arr 
# random  in btwn 0 - 1 , randomly initialize 

array([0.39032188, 0.50413509, 0.97666491, 0.28331004, 0.17945325,
       0.55719043, 0.53923883, 0.84881171, 0.13958088, 0.06605548])

In [20]:
arr = np.random.random((5,4))
arr 

array([[0.25816394, 0.58075813, 0.87812812, 0.49217009],
       [0.69704626, 0.25792071, 0.81960321, 0.20464543],
       [0.32365181, 0.72674162, 0.4085167 , 0.26799324],
       [0.50260828, 0.95306626, 0.30395396, 0.55256371],
       [0.91930127, 0.14853317, 0.13181526, 0.87397353]])

In [21]:
arr = np.random.random((2,5,4))
arr 

array([[[0.64792167, 0.76898922, 0.37820177, 0.77269022],
        [0.23087093, 0.56862604, 0.89817592, 0.44206551],
        [0.13450433, 0.6051332 , 0.87875556, 0.10321474],
        [0.06357977, 0.12543041, 0.61358172, 0.21798282],
        [0.69155179, 0.15854466, 0.35284685, 0.25241574]],

       [[0.4448689 , 0.3481584 , 0.75289495, 0.49546332],
        [0.2039677 , 0.64559687, 0.20869988, 0.23500596],
        [0.88202084, 0.43720975, 0.55548523, 0.62499545],
        [0.2547685 , 0.7048988 , 0.67811451, 0.36207991],
        [0.42750897, 0.90668304, 0.19971133, 0.06711717]]])

In [24]:
arr = np.arange(1,11)  # it will create 1D array in a specified range 
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr = np.ones(5)
arr 

array([1., 1., 1., 1., 1.])

In [28]:
arr = np.ones((5,4))
arr 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr = np.zeros((5,4))
arr 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
arr.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
arr.dtype

dtype('float64')

In [33]:
arr = np.linspace(1,10,5)
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
arr = np.random.randint(1,12,10)
arr 

array([ 8,  6,  4, 11, 11,  4, 10, 10,  7,  3], dtype=int32)

In [37]:
np.sum(arr)

np.int64(74)

In [50]:
## aggregation function 
variance = arr.var()  # std()    #var()     #mean()    # mean ==average ,  #sum()     #max()   #min()
np.sqrt(variance)

np.float64(2.90516780926679)

In [52]:
np.power(2,3)

np.int64(8)

In [55]:
print(arr)
print(np.cumsum(arr))  # cumulative sum 

[ 8  6  4 11 11  4 10 10  7  3]
[ 8 14 18 29 40 44 54 64 71 74]


In [ ]:
arr.sort()  # ascending order 

In [58]:
arr 

array([ 3,  4,  4,  6,  7,  8, 10, 10, 11, 11], dtype=int32)

In [59]:
arr[::-1]  # descending order 

array([11, 11, 10, 10,  8,  7,  6,  4,  4,  3], dtype=int32)

In [60]:
arr = np.random.randint(1,12,10)
arr 

array([10,  4,  6,  2,  1,  1,  6, 11,  8,  5], dtype=int32)

In [ ]:
arr[2] = 60  # to update the items 

In [66]:
arr 

array([10,  4, 60,  2,  1,  1,  6, 11,  8,  5], dtype=int32)

In [67]:
arr[1:3] = 100

In [68]:
arr 

array([ 10, 100, 100,   2,   1,   1,   6,  11,   8,   5], dtype=int32)

In [69]:
arr 

array([ 10, 100, 100,   2,   1,   1,   6,  11,   8,   5], dtype=int32)

In [70]:
arr = np.array([8,7,9])
arr 

array([8, 7, 9])

In [74]:
arr.argsort()      #argmax()    #argmin()

array([1, 0, 2])

In [75]:
arr = np.random.randint(1,50,(3,5,4))
arr 

array([[[43, 31, 20, 43],
        [16,  6, 29, 23],
        [48, 36,  5,  5],
        [45, 48, 46, 13],
        [29, 27, 46, 17]],

       [[37, 25,  7, 38],
        [18, 26, 25, 16],
        [11, 12,  5, 42],
        [ 5, 11, 44, 43],
        [41, 40, 49, 41]],

       [[47, 25,  5, 25],
        [20, 26, 42,  1],
        [15,  1, 23, 15],
        [47, 49, 49, 47],
        [37, 29, 16, 27]]], dtype=int32)

In [79]:
arr.ravel()   # convert into 1D 

array([43, 31, 20, 43, 16,  6, 29, 23, 48, 36,  5,  5, 45, 48, 46, 13, 29,
       27, 46, 17, 37, 25,  7, 38, 18, 26, 25, 16, 11, 12,  5, 42,  5, 11,
       44, 43, 41, 40, 49, 41, 47, 25,  5, 25, 20, 26, 42,  1, 15,  1, 23,
       15, 47, 49, 49, 47, 37, 29, 16, 27], dtype=int32)

In [81]:
arr.flatten()

array([43, 31, 20, 43, 16,  6, 29, 23, 48, 36,  5,  5, 45, 48, 46, 13, 29,
       27, 46, 17, 37, 25,  7, 38, 18, 26, 25, 16, 11, 12,  5, 42,  5, 11,
       44, 43, 41, 40, 49, 41, 47, 25,  5, 25, 20, 26, 42,  1, 15,  1, 23,
       15, 47, 49, 49, 47, 37, 29, 16, 27], dtype=int32)

In [89]:
arr.reshape(60) #   3*5*4 = 60 

array([43, 31, 20, 43, 16,  6, 29, 23, 48, 36,  5,  5, 45, 48, 46, 13, 29,
       27, 46, 17, 37, 25,  7, 38, 18, 26, 25, 16, 11, 12,  5, 42,  5, 11,
       44, 43, 41, 40, 49, 41, 47, 25,  5, 25, 20, 26, 42,  1, 15,  1, 23,
       15, 47, 49, 49, 47, 37, 29, 16, 27], dtype=int32)

In [88]:
arr.size   # total no, of items 

60

In [90]:
arr.reshape(10,6)

array([[43, 31, 20, 43, 16,  6],
       [29, 23, 48, 36,  5,  5],
       [45, 48, 46, 13, 29, 27],
       [46, 17, 37, 25,  7, 38],
       [18, 26, 25, 16, 11, 12],
       [ 5, 42,  5, 11, 44, 43],
       [41, 40, 49, 41, 47, 25],
       [ 5, 25, 20, 26, 42,  1],
       [15,  1, 23, 15, 47, 49],
       [49, 47, 37, 29, 16, 27]], dtype=int32)

In [94]:
arr.reshape(20,4)  # resize()

ValueError: cannot reshape array of size 60 into shape (20,4)

In [96]:
np.resize(arr,(20,4))   # duplicates 

array([[43, 31, 20, 43],
       [16,  6, 29, 23],
       [48, 36,  5,  5],
       [45, 48, 46, 13],
       [29, 27, 46, 17],
       [37, 25,  7, 38],
       [18, 26, 25, 16],
       [11, 12,  5, 42],
       [ 5, 11, 44, 43],
       [41, 40, 49, 41],
       [47, 25,  5, 25],
       [20, 26, 42,  1],
       [15,  1, 23, 15],
       [47, 49, 49, 47],
       [37, 29, 16, 27],
       [43, 31, 20, 43],
       [16,  6, 29, 23],
       [48, 36,  5,  5],
       [45, 48, 46, 13],
       [29, 27, 46, 17]], dtype=int32)

In [97]:
arr = np.random.randint(1,12,11)
arr 

array([ 8,  5,  2,  6,  5,  8,  4, 11,  4, 11,  1], dtype=int32)

In [101]:
arr = np.random.randint(1,50,(5,3))
arr 

array([[12, 20, 46],
       [30, 36, 12],
       [ 8,  3,  6],
       [ 2,  4, 34],
       [16, 42, 36]], dtype=int32)

In [102]:
np.transpose(arr)   # are same ==>   arr.T   

array([[12, 30,  8,  2, 16],
       [20, 36,  3,  4, 42],
       [46, 12,  6, 34, 36]], dtype=int32)

In [104]:
arr.T    # transpose 

array([[12, 30,  8,  2, 16],
       [20, 36,  3,  4, 42],
       [46, 12,  6, 34, 36]], dtype=int32)

In [106]:
## metrics operation 
arr = np.random.randint(1,50,10)
print(arr )
print(arr + 2 )

[42 10 20 27 29 14 44 36 25  4]
[44 12 22 29 31 16 46 38 27  6]


In [107]:
print(arr)
print(arr * 2)

[42 10 20 27 29 14 44 36 25  4]
[84 20 40 54 58 28 88 72 50  8]


In [114]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([5,5,5,5])
print(arr1)
print(arr2)

[10 20 30 40]
[5 5 5 5]


In [116]:
print(arr1)
print(arr2)
print(arr1 + arr2) 

[10 20 30 40]
[5 5 5 5]
[15 25 35 45]


In [3]:
arr = np.random.randint(1,200,200)
arr 

array([ 24, 101,  50,  33,  32, 158,  76, 198, 124,  99,  36, 193, 198,
       150, 114, 178, 150, 168, 142, 130,  89, 193, 155, 136, 154, 168,
       143,  14, 178,  90, 117,  92, 150,  84,  29,  92, 115, 190,  29,
       174,  72,  32, 198,  74, 156,  19,  24, 135, 196, 102,  60, 149,
         5,  46,  31, 125, 126, 104, 105,  16,  52,  23,  63,   3,  76,
       195, 194,   5,  66,  34, 161, 103,  36,  41,  74,  32,  83, 109,
        11, 120, 125, 133, 181, 122, 184,  61,  18, 122, 196, 134, 182,
        88,  18, 193, 148, 131, 189, 149, 150,  83,  82,  95,  35,  38,
        45,  34,  19, 139, 131,  89,  37,  56, 123, 150, 141, 119,  62,
        61, 168, 121, 110, 123, 137, 167,  87,  46,  82, 146, 175,  96,
       196, 165,  47,  23,   1,  43, 178, 143, 106, 117, 125, 141, 185,
        31,  48,  55,  78, 151,  40, 119, 154, 165,  30,  51,  21,  42,
        26, 163,  79, 148, 184, 103, 143, 151, 173,  64,  66, 190,  54,
        20, 188, 187,  49, 185, 180,  60, 115,  42,  66, 125, 18

In [6]:
temp = []
for item in arr:
    if item < 100 :
        temp.append(int(item))
print(temp)
print(len(temp))    

[24, 50, 33, 32, 76, 99, 36, 89, 14, 90, 92, 84, 29, 92, 29, 72, 32, 74, 19, 24, 60, 5, 46, 31, 16, 52, 23, 63, 3, 76, 5, 66, 34, 36, 41, 74, 32, 83, 11, 61, 18, 88, 18, 83, 82, 95, 35, 38, 45, 34, 19, 89, 37, 56, 62, 61, 87, 46, 82, 96, 47, 23, 1, 43, 31, 48, 55, 78, 40, 30, 51, 21, 42, 26, 79, 64, 66, 54, 20, 49, 60, 42, 66, 24, 29, 24, 43, 59, 87]
89


In [10]:
arr[arr > 100]    # try with multiple 

array([101, 158, 198, 124, 193, 198, 150, 114, 178, 150, 168, 142, 130,
       193, 155, 136, 154, 168, 143, 178, 117, 150, 115, 190, 174, 198,
       156, 135, 196, 102, 149, 125, 126, 104, 105, 195, 194, 161, 103,
       109, 120, 125, 133, 181, 122, 184, 122, 196, 134, 182, 193, 148,
       131, 189, 149, 150, 139, 131, 123, 150, 141, 119, 168, 121, 110,
       123, 137, 167, 146, 175, 196, 165, 178, 143, 106, 117, 125, 141,
       185, 151, 119, 154, 165, 163, 148, 184, 103, 143, 151, 173, 190,
       188, 187, 185, 180, 115, 125, 189, 110, 182, 181, 158, 192, 112,
       184, 147, 101, 110, 145, 143, 176], dtype=int32)

In [14]:
arr = np.random.randint(1,40,20)
np.where(arr<10)  # data  filter 

(array([ 2, 10, 11, 15]),)

In [15]:
arr 

array([29, 19,  4, 31, 23, 25, 36, 37, 33, 34,  1,  4, 38, 26, 27,  2, 18,
       17, 20, 38], dtype=int32)

In [16]:
arr1 = np.random.randint(1,20,5)
arr2 = np.random.randint(1,20,5)
print(arr1)
print(arr2)

[ 2 10 11 17 13]
[11  8 11 11 12]


In [19]:
arr3 = np.concatenate((arr1,arr2))
arr3

array([ 2, 10, 11, 17, 13, 11,  8, 11, 11, 12], dtype=int32)

In [29]:
# 2D + 2D 
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,(5,1))
print(arr1)
print()
print(arr2)

[[13 11  2  9]
 [19  7 13 16]
 [14  1 17  7]
 [ 9 11  7 11]
 [19 13  6  1]]

[[ 9]
 [15]
 [ 9]
 [14]
 [17]]


In [30]:
np.concatenate((arr1,arr2),axis=1)

array([[13, 11,  2,  9,  9],
       [19,  7, 13, 16, 15],
       [14,  1, 17,  7,  9],
       [ 9, 11,  7, 11, 14],
       [19, 13,  6,  1, 17]], dtype=int32)

In [35]:
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,(4,1))
print(arr1)
print()
print(arr2)

[[16  6  9  4]
 [11 14 16 15]
 [11 10  8  9]
 [ 8 14 11  1]
 [ 1 15  8 12]]

[[ 5]
 [11]
 [11]
 [18]]


In [38]:
np.concatenate((arr1,arr2.T),axis=0)

array([[16,  6,  9,  4],
       [11, 14, 16, 15],
       [11, 10,  8,  9],
       [ 8, 14, 11,  1],
       [ 1, 15,  8, 12],
       [ 5, 11, 11, 18]], dtype=int32)

In [39]:
# 2D + 1D 
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)

[[17 11  3 19]
 [10 13 16  5]
 [ 8  9 17  9]
 [ 1  5  3 19]
 [10 17  5 19]]

[ 4 10 13 11]


In [40]:
arr1.shape , arr2.shape 

((5, 4), (4,))

In [43]:
np.vstack((arr1,arr2))


array([[17, 11,  3, 19],
       [10, 13, 16,  5],
       [ 8,  9, 17,  9],
       [ 1,  5,  3, 19],
       [10, 17,  5, 19],
       [ 4, 10, 13, 11]], dtype=int32)

In [ ]:
np.vsplit()
np.hsplit() 