In [1]:
print("hello world")

hello world


In [4]:
import numpy as np 

In [5]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr.dtype

dtype('int64')

In [9]:
arr = np.array([10,20,30,40,50,20.2])   # to create an array 
arr 

array([10. , 20. , 30. , 40. , 50. , 20.2])

In [10]:
arr = np.array([10,20,30,40,50,"Upflairs"])   # to create an array 
arr 

array(['10', '20', '30', '40', '50', 'Upflairs'], dtype='<U21')

In [13]:
arr.ndim    # dimension of array 

1

In [14]:
arr = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])   # [ [1d] , [1d] , [1D] , [1D]  ]
arr 

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [18]:
ls = [[[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]]]

# print(ls)
# print(type(ls))
arr = np.array(ls)
arr 

array([[[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [19]:
type(arr)

numpy.ndarray

In [20]:
arr.ndim 

3

In [21]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [23]:
arr[-2]  # single item 

np.int64(40)

In [27]:
arr[::3]

array([10, 40])

In [28]:
arr[::1]

array([10, 20, 30, 40, 50])

In [29]:
arr[::-1]


array([50, 40, 30, 20, 10])